"""empty message

Revision ID: 13162f206c51
Revises: 7157849c973b
Create Date: 2019-05-21 15:08:17.122195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13162f206c51'
down_revision = '7157849c973b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation', sa.String(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.PrimaryKeyConstraint('quotation_id')
    )
    op.add_column('answers', sa.Column('quotation_id', sa.Integer(), nullable=True))
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('answers', 'quotation_id')
    op.drop_table('quotations')
    # ### end Alembic commands ###
