"""empty message

Revision ID: 1ef8bc666dc4
Revises: 97f511d30c34
Create Date: 2019-05-24 12:25:38.219209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef8bc666dc4'
down_revision = '97f511d30c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('answers', sa.Column('party_id_guess', sa.Integer(), nullable=True))
    op.drop_constraint('answers_party_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'parties', ['party_id_guess'], ['party_id'])
    op.drop_column('answers', 'party_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_party_id_fkey', 'answers', 'parties', ['party_id'], ['party_id'])
    op.drop_column('answers', 'party_id_guess')
    op.drop_column('answers', 'created_at')
    # ### end Alembic commands ###
