"""empty message

Revision ID: 42617146dfe6
Revises: 1ef8bc666dc4
Create Date: 2019-05-25 13:28:53.366405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42617146dfe6'
down_revision = '1ef8bc666dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotations')
    op.drop_table('sessions')
    op.drop_table('parties')
    op.drop_table('answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('answer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('party_id_guess', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id_guess'], ['parties.party_id'], name='answers_party_id_guess_fkey'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.quotation_id'], name='answers_quotation_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='answers_session_id_fkey'),
    sa.PrimaryKeyConstraint('answer_id', name='answers_pkey')
    )
    op.create_table('parties',
    sa.Column('party_id', sa.INTEGER(), server_default=sa.text("nextval('parties_party_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('party_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('party_id', name='parties_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sessions',
    sa.Column('session_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], name='sessions_party_id_fkey'),
    sa.PrimaryKeyConstraint('session_id', name='sessions_pkey')
    )
    op.create_table('quotations',
    sa.Column('quotation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quotation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], name='quotations_party_id_fkey'),
    sa.PrimaryKeyConstraint('quotation_id', name='quotations_pkey')
    )
    # ### end Alembic commands ###
