"""empty message

Revision ID: 43df266be83d
Revises: 
Create Date: 2019-05-20 12:01:33.057757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43df266be83d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parties')
    # ### end Alembic commands ###
