"""empty message

Revision ID: 51a39eba8c2c
Revises: 7bd0013672bc
Create Date: 2019-05-20 13:06:53.455821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a39eba8c2c'
down_revision = '7bd0013672bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('sessions')
    op.drop_table('parties')
    # ### end Alembic commands ###
