"""empty message

Revision ID: 97f511d30c34
Revises: 13162f206c51
Create Date: 2019-05-21 15:14:00.397150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f511d30c34'
down_revision = '13162f206c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answers', 'quotations', ['quotation_id'], ['quotation_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    # ### end Alembic commands ###
